import { useState, useMemo } from 'react'
import {
  Card, CardContent, CardHeader, CardTitle,
} from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { useDatasetStore } from '@/store/datasetStore'
import { FileText, Copy, Check } from 'lucide-react'

const hypothesisTemplates: Record<string, { h0: string; h1: string }> = {
  'Z-Test': { h0: 'μ = μ₀ (population mean equals hypothesized value)', h1: 'μ ≠ μ₀ (population mean differs from hypothesized value)' },
  'One-Sample T-Test': { h0: 'μ = μ₀ (population mean equals hypothesized value)', h1: 'μ ≠ μ₀ (population mean differs from hypothesized value)' },
  'Independent T-Test': { h0: 'μ₁ = μ₂ (group means are equal)', h1: 'μ₁ ≠ μ₂ (group means are not equal)' },
  'Paired T-Test': { h0: 'μ_d = 0 (mean difference is zero)', h1: 'μ_d ≠ 0 (mean difference is not zero)' },
  'ANOVA': { h0: 'μ₁ = μ₂ = ... = μₖ (all group means are equal)', h1: 'At least one group mean differs' },
  'Two-Way ANOVA': { h0: 'No main effects or interaction', h1: 'At least one main effect or interaction exists' },
  'Chi-Square Goodness of Fit': { h0: 'Observed frequencies match expected distribution', h1: 'Observed frequencies differ from expected distribution' },
  'Chi-Square Independence': { h0: 'Variables are independent', h1: 'Variables are associated (not independent)' },
  'Mann-Whitney': { h0: 'The two populations have the same distribution', h1: 'The two populations differ in location' },
  'Wilcoxon': { h0: 'Median difference is zero', h1: 'Median difference is not zero' },
  'Kruskal-Wallis': { h0: 'All groups have the same median', h1: 'At least one group median differs' },
  'Friedman': { h0: 'All treatments have the same effect', h1: 'At least one treatment differs' },
  'Correlation': { h0: 'ρ = 0 (no linear correlation)', h1: 'ρ ≠ 0 (linear correlation exists)' },
  'Normality': { h0: 'Data follows a normal distribution', h1: 'Data does not follow a normal distribution' },
  'CLT': { h0: 'Sample means follow a normal distribution (CLT holds)', h1: '-' },
}

function inferTemplate(action: string): { template: string; details: string } {
  for (const [key] of Object.entries(hypothesisTemplates)) {
    if (action.includes(key)) return { template: key, details: action }
  }
  if (action.includes('Descriptive')) return { template: 'Descriptive', details: action }
  return { template: 'General', details: action }
}

export default function ReportGenerator() {
  const { fullData, columnMetadata, activityLog } = useDatasetStore()
  const [selectedId, setSelectedId] = useState('')
  const [copied, setCopied] = useState(false)

  const selectedEntry = activityLog.find((e) => e.id === selectedId)

  const report = useMemo(() => {
    if (!selectedEntry) return null
    const { template, details } = inferTemplate(selectedEntry.action)
    const hyps = hypothesisTemplates[template]
    return {
      title: `${selectedEntry.action} — ${new Date(selectedEntry.timestamp).toLocaleString()}`,
      details,
      h0: hyps?.h0 || 'H₀: No effect / no difference',
      h1: hyps?.h1 || 'H₁: Effect exists / difference exists',
      significance: 0.05,
    }
  }, [selectedEntry])

  const reportText = useMemo(() => {
    if (!report) return ''
    return [
      '='.repeat(60),
      `  STATTOOLKIT — Statistical Analysis Report`,
      '='.repeat(60),
      '',
      `  Analysis: ${report.title}`,
      `  Dataset: ${fullData.length} rows, ${columnMetadata.length} columns`,
      '',
      '─'.repeat(60),
      '  HYPOTHESIS TEST',
      '─'.repeat(60),
      '',
      `  H₀: ${report.h0}`,
      `  H₁: ${report.h1}`,
      `  α = ${report.significance}`,
      '',
      `  ${report.details}`,
      '',
      '─'.repeat(60),
      '  INTERPRETATION',
      '─'.repeat(60),
      '',
      `  Based on the computed test statistic and p-value compared to α = ${report.significance}:`,
      `  • If p-value < α: Reject H₀ — there is statistically significant evidence to support H₁.`,
      `  • If p-value ≥ α: Fail to reject H₀ — insufficient evidence to support H₁.`,
      '',
      '─'.repeat(60),
      '  CONCLUSION',
      '─'.repeat(60),
      '',
      '  This report was auto-generated by StatToolkit.',
      '  Always consider practical significance alongside statistical significance.',
      '',
      '='.repeat(60),
    ].join('\n')
  }, [report, fullData.length, columnMetadata.length])

  const copyReport = async () => {
    await navigator.clipboard.writeText(reportText)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="space-y-8">
      <div className="flex items-center gap-3">
        <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-indigo-500 via-purple-500 to-pink-500 shadow-lg shadow-purple-500/30">
          <FileText className="h-5 w-5 text-white" />
        </div>
        <div>
          <h1 className="text-2xl font-bold text-white">Report Generator</h1>
          <p className="text-sm text-muted">Auto-generated hypothesis tables, interpretations & exportable reports</p>
        </div>
      </div>

      {activityLog.length === 0 ? (
        <Card><CardContent className="py-12 text-center text-muted">Run some analyses first to generate reports from them.</CardContent></Card>
      ) : (
        <>
          <Card>
            <CardHeader><CardTitle className="text-sm">Select Analysis</CardTitle></CardHeader>
            <CardContent>
              <Select value={selectedId} onValueChange={setSelectedId}>
                <SelectTrigger><SelectValue placeholder="Choose a recent analysis..." /></SelectTrigger>
                <SelectContent>
                  {activityLog.slice(0, 50).map((e) => (
                    <SelectItem key={e.id} value={e.id}>
                      {e.action} — {new Date(e.timestamp).toLocaleTimeString()}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </CardContent>
          </Card>

          {report && (
            <Card>
              <CardHeader className="flex flex-row items-center justify-between">
                <CardTitle className="text-sm">{report.title}</CardTitle>
                <Button size="sm" variant="outline" onClick={copyReport} className="gap-2">
                  {copied ? <Check className="h-4 w-4 text-emerald-400" /> : <Copy className="h-4 w-4" />}
                  {copied ? 'Copied' : 'Copy Report'}
                </Button>
              </CardHeader>
              <CardContent>
                <div className="rounded-xl border border-glass-border bg-surface/80 p-5">
                  <div className="mb-4">
                    <p className="text-xs font-medium text-muted uppercase tracking-wider">Hypothesis Table</p>
                  </div>
                  <table className="w-full text-sm">
                    <tbody>
                      <tr className="border-b border-glass-border">
                        <td className="py-2.5 pr-6 font-medium text-white/80">Null Hypothesis (H₀)</td>
                        <td className="py-2.5 text-white">{report.h0}</td>
                      </tr>
                      <tr className="border-b border-glass-border">
                        <td className="py-2.5 pr-6 font-medium text-white/80">Alternative Hypothesis (H₁)</td>
                        <td className="py-2.5 text-white">{report.h1}</td>
                      </tr>
                      <tr className="border-b border-glass-border">
                        <td className="py-2.5 pr-6 font-medium text-white/80">Significance Level (α)</td>
                        <td className="py-2.5 text-white">{report.significance}</td>
                      </tr>
                      <tr className="border-b border-glass-border">
                        <td className="py-2.5 pr-6 font-medium text-white/80">Analysis Details</td>
                        <td className="py-2.5 text-white/70">{report.details}</td>
                      </tr>
                    </tbody>
                  </table>

                  <div className="mt-6">
                    <p className="text-xs font-medium text-muted uppercase tracking-wider mb-3">Auto-Conclusion</p>
                    <div className="rounded-lg border border-glass-border bg-white/[0.02] p-4">
                      <p className="text-sm leading-relaxed text-white/80">
                        A <strong className="text-white">{selectedEntry?.action || 'statistical'}</strong> test was conducted
                        on <strong className="text-white">{fullData.length}</strong> observations with
                        <strong className="text-white"> {columnMetadata.length}</strong> variables.
                        The test statistic and corresponding p-value were evaluated against α = 0.05.
                        {` `}
                        <strong className="text-accent">
                          {selectedEntry?.action?.toLowerCase().includes('t-test') || selectedEntry?.action?.toLowerCase().includes('z-test') || selectedEntry?.action?.toLowerCase().includes('anova') || selectedEntry?.action?.toLowerCase().includes('chi-square') || selectedEntry?.action?.toLowerCase().includes('mann') || selectedEntry?.action?.toLowerCase().includes('wilcoxon') || selectedEntry?.action?.toLowerCase().includes('kruskal') || selectedEntry?.action?.toLowerCase().includes('friedman')
                            ? 'If p < 0.05, we reject H₀ and conclude there is statistically significant evidence for the alternative hypothesis.'
                            : selectedEntry?.action?.toLowerCase().includes('correlation')
                            ? 'If p < 0.05, we conclude a statistically significant linear correlation exists between the variables.'
                            : selectedEntry?.action?.toLowerCase().includes('normality')
                            ? 'If p < 0.05, the data significantly deviates from a normal distribution.'
                            : 'Statistical significance was assessed at the 95% confidence level.'}
                        </strong>
                      </p>
                    </div>
                  </div>

                  <div className="mt-6">
                    <Button variant="outline" size="sm" onClick={copyReport} className="gap-2">
                      <Copy className="h-4 w-4" />
                      Copy Full Report
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          )}
        </>
      )}
    </div>
  )
}
